### ISSUE TITLE
Opening multiple projects with different core versions can confuse the LanguageModelContainer

### ISSUE THREAD

**Issue by UndefinedOffset** [UndefinedOffset/eclipse-silverstripedt#72]
For some reason opening multiple projects with different core versions can confuse the LanguageModelContainer. This can also occur when importing a project,

**Comment by UndefinedOffset** [comment]
Possibly related:

```
java.lang.IllegalArgumentException: Attempted to beginRule: P/.org.eclipse.dltk.core.external.folders, does not match outer scope rule: P/Project Name
	at org.eclipse.core.runtime.Assert.isLegal(Assert.java:63)
	at org.eclipse.core.internal.jobs.ThreadJob.illegalPush(ThreadJob.java:134)
	at org.eclipse.core.internal.jobs.ThreadJob.push(ThreadJob.java:389)
	at org.eclipse.core.internal.jobs.ImplicitJobs.begin(ImplicitJobs.java:63)
	at org.eclipse.core.internal.jobs.JobManager.beginRule(JobManager.java:308)
	at org.eclipse.core.internal.resources.WorkManager.checkIn(WorkManager.java:121)
	at org.eclipse.core.internal.resources.Workspace.prepareOperation(Workspace.java:2237)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1539)
	at org.eclipse.dltk.internal.core.ExternalFoldersManager.createLinkFolder(ExternalFoldersManager.java:137)
	at org.eclipse.dltk.internal.core.ExternalFolderChange.updateExternalFoldersIfNecessary(ExternalFolderChange.java:50)
	at org.eclipse.dltk.internal.core.ChangeBuildpathOperation.buildpathChanged(ChangeBuildpathOperation.java:71)
	at org.eclipse.dltk.internal.core.SetContainerOperation.executeOperation(SetContainerOperation.java:154)
	at org.eclipse.dltk.internal.core.ModelOperation.run(ModelOperation.java:703)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2289)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2316)
	at org.eclipse.dltk.internal.core.ModelOperation.runOperation(ModelOperation.java:778)
	at org.eclipse.dltk.core.DLTKCore.setBuildpathContainer(DLTKCore.java:1969)
	at ca.edchipman.silverstripepdt.language.LanguageModelInitializer.initialize(LanguageModelInitializer.java:103)
	at ca.edchipman.silverstripepdt.language.LanguageModelInitializer$1.preferencesEventOccured(LanguageModelInitializer.java:77)
	at ca.edchipman.silverstripepdt.language.SilverStripeVersionChangedHandler.projectVersionChanged(SilverStripeVersionChangedHandler.java:47)
	at ca.edchipman.silverstripepdt.language.SilverStripeVersionChangedHandler.access$0(SilverStripeVersionChangedHandler.java:41)
	at ca.edchipman.silverstripepdt.language.SilverStripeVersionChangedHandler$PreferencesPropagatorListener.preferencesEventOccured(SilverStripeVersionChangedHandler.java:83)
	at org.eclipse.php.internal.core.preferences.ProjectPreferencesPropagator.notifyEvent(ProjectPreferencesPropagator.java:133)
	at org.eclipse.php.internal.core.preferences.ProjectPreferencesPropagator.notifyPropagatorEvent(ProjectPreferencesPropagator.java:109)
	at org.eclipse.php.internal.core.preferences.ProjectPreferencesPropagator.access$0(ProjectPreferencesPropagator.java:108)
	at org.eclipse.php.internal.core.preferences.ProjectPreferencesPropagator$InnerPreferenceChangeListener.preferenceChange(ProjectPreferencesPropagator.java:156)
	at org.eclipse.core.internal.preferences.EclipsePreferences$2.run(EclipsePreferences.java:845)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.preferences.EclipsePreferences.firePreferenceEvent(EclipsePreferences.java:848)
	at org.eclipse.core.internal.preferences.EclipsePreferences.convertFromProperties(EclipsePreferences.java:256)
	at org.eclipse.core.internal.resources.ProjectPreferences.load(ProjectPreferences.java:512)
	at org.eclipse.core.internal.resources.ProjectPreferences.silentLoad(ProjectPreferences.java:688)
	at org.eclipse.core.internal.resources.ProjectPreferences.keys(ProjectPreferences.java:489)
	at org.eclipse.core.internal.preferences.PreferencesService$1.visit(PreferencesService.java:156)
	at org.eclipse.core.internal.preferences.EclipsePreferences.accept(EclipsePreferences.java:113)
	at org.eclipse.core.internal.preferences.PreferencesService.applyPreferences(PreferencesService.java:198)
	at org.eclipse.core.internal.resources.ProjectPreferences.read(ProjectPreferences.java:209)
	at org.eclipse.core.internal.resources.ProjectPreferences.updatePreferences(ProjectPreferences.java:277)
	at org.eclipse.core.internal.resources.File.updateMetadataFiles(File.java:387)
	at org.eclipse.core.internal.localstore.RefreshLocalVisitor.visit(RefreshLocalVisitor.java:288)
	at org.eclipse.core.internal.localstore.UnifiedTree.accept(UnifiedTree.java:110)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refreshResource(FileSystemResourceManager.java:973)
	at org.eclipse.core.internal.localstore.FileSystemResourceManager.refresh(FileSystemResourceManager.java:956)
	at org.eclipse.core.internal.resources.Resource.refreshLocal(Resource.java:1547)
	at org.eclipse.core.internal.refresh.RefreshJob.runInWorkspace(RefreshJob.java:163)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:60)
```
